server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index /painel-admin/index.html;

    location = /painel-admin {
        return 301 /painel-admin/;
    }

    location /painel-admin/ {
        try_files $uri $uri/ /painel-admin/index.html;
    }
}
